AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Fn::FindInMap:
          - "RegionMap"
          - Ref: "AWS::Region"
          - "AMI"
      KeyName: SamOregonEC2
      InstanceShutdownBehavior: stop
      InstanceType: 
