AWSTemplateFormatVersion: 2010-09-09
Description: "Creation of VPC using the Cloud Formation Template"
Resources:
  MyVpcUsingCloudFormation:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"