AWSTemplateFormatVersion: 2010-09-09


Description: "Creation of VPC using the Cloud Formation Template"


Parameters:
  DbSubnetIpBlocks:
    Description: "CIDR blocks for MyPublicSubnet"
    Type: String
  DbSubnetIpBlocks1:
    Description: "CIDR blocks for MyPrivateSubnet"
    Type: String

  
Resources:

  MyVpcUsingCloudFormation:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      Tags:
        -
          Key: "Name"
          Value: "MyVpcWithCF"
        -
          Key: "Client"
          Value: "CTR"

  MyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVpcUsingCloudFormation
      CidrBlock: !Ref DbSubnetIpBlocks
      Tags:
        -
          Key: "Name"
          Value: "MyPublicSubnet"
        -
          Key: "Client"
          Value: "CTR"

  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVpcUsingCloudFormation
      CidrBlock: !Ref DbSubnetIpBlocks1
      Tags:
        -
          Key: "Name"
          Value: "MyPrivateSubnet"
        -
          Key: "Client"
          Value: "CTR"

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        -
          Key: "Name"
          Value: "MyInternetGateway"
        -
          Key: "Client"
          Value: "CTR"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVpcUsingCloudFormation
      InternetGatewayId: !Ref MyInternetGateway

  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVpcUsingCloudFormation
      Tags:
        -
          Key: "Name"
          Value: "MyRouteTable"
        -
          Key: "Client"
          Value: "CTR"

  MyRoute:
    Type: AWS::EC2::RouteTable
    DependsOn: MyInternetGateway
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway
      RouteTableId: !Ref MyRouteTable


Outputs:
  VpcId:
    Value: !Ref MyVpcUsingCloudFormation
  PrimaryCidrBlock:
    Value: !GetAtt MyVpcUsingCloudFormation.CidrBlock
  MyPublicSubnetId: 
    Value: !Ref MyPublicSubnet
  MyPrivateSubnetId:
    Value: !Ref MyPrivateSubnet
  MyInternetGateway:
    Value: !Ref MyInternetGateway
    